language: java

sudo: required

jdk:
  - oraclejdk8

script: 
  mvn clean install verify test
  
before_deploy:
  - "mvn -DskipTests package"
  - export RESTING=$(ls target/resting-*.jar)

deploy:
  provider: releases
  file: "${RESTING}"